# Created 2021-09-29 Wed 20:29
#+TITLE: GDYARN
#+AUTHOR: Jonathan Camarena (kyperbelt)

* Contents
- [[#Introduction][Introduction]]
- [[#Features][Features]]
- [[#Installation][Installation]]
- [[#Quickstart][Quickstart]]

* Introduction
:PROPERTIES:
:CUSTOM_ID: Introduction
:END:
GD Yarn is an godot plugin that allows you to create rich and interative dialogues using a simple markup language similar to twine. It is easy to get started writing simple scripts, but powerful enough to your games dialogue to the next level with branching narratives that can change based on the players actions.

GD yarn is an implementation of [[https://yarnspinner.dev][YarnSpinner]] completely written in gdscript. The project aims to be as feature complete as possible compared to the c# version but may forgoe certain things in lieu of similar alternatives that make it blend better with the godot ecosystem.

* Features
:PROPERTIES:
:CUSTOM_ID: Features
:END:
- [X] Compile multiple Yarn files into a single Program
- [-] Persistent Variable Storage
- [-] Custom Commands
- [X] Libary Extensions
- [X] Format functions
- [X] Option Links
- [X] Shortcut Options
- [-] Localization
- [X] IF/ELSE Statements

* Installation
:PROPERTIES:
:CUSTOM_ID: Installation
:END:
** Install from AssetLib
** Install from GitHub

* Quickstart
:PROPERTIES:
:CUSTOM_ID: Quickstart
:END:
** Setup
After you have installed the plugin (*by putting the gdyarn folder in the addons directory*), make sure that the addon is enabled in the `ProjectSettings -> Plugins` tab.

** Running your first yarn program
You must include a YarnRunner node to the project
